add_subdirectory(01-cpp-foundations)
add_subdirectory(03-lifetime-raii)
add_subdirectory(04-polymorphism)
add_subdirectory(05-function-templates)
add_subdirectory(07-error-handling)
add_subdirectory(08-sequence-containers)
add_subdirectory(09-associative-containers)
add_subdirectory(10-algorithms-lambdas)
add_subdirectory(11-iterators-ranges)
add_subdirectory(15-behavioral-patterns)
add_subdirectory(16-structural-patterns)
